apiVersion: v1
kind: PersistentVolume
metadata:
  name: dr0001
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  vsphereVolume:
    volumePath: "[vnxfs1] kubevols/dr0001"
    fsType: ext4
