kind: Deployment
apiVersion: apps/v1
metadata:
  name: app1
  namespace: kiodo
  labels:
        app: webfront
spec:
  replicas: 1
  template:      
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: app2
  namespace: kiodo
  labels:
        app: db
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
